
# This file is automatically generated, you probably don't want to edit this

showFileOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "showFileOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            file = NULL,
            files = NULL, ...) {

            super$initialize(
                package="filetest",
                name="showFile",
                requiresData=TRUE,
                ...)

            private$..file <- jmvcore::OptionFile$new(
                "file",
                file,
                extensions=list(
                    "txt",
                    "csv",
                    "md"))
            private$..files <- jmvcore::OptionFile$new(
                "files",
                files,
                multiple=TRUE)

            self$.addOption(private$..file)
            self$.addOption(private$..files)
        }),
    active = list(
        file = function() private$..file$value,
        files = function() private$..files$value),
    private = list(
        ..file = NA,
        ..files = NA)
)

showFileResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "showFileResults",
    inherit = jmvcore::Group,
    active = list(
        content = function() private$.items[["content"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Show File")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="content",
                title="Content"))}))

showFileBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "showFileBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "filetest",
                name = "showFile",
                version = c(1,0,0),
                options = options,
                results = showFileResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Show File
#'
#' 
#' @param data .
#' @param file .
#' @param files .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$content} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
showFile <- function(
    data,
    file = NULL,
    files = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("showFile requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- showFileOptions$new(
        file = file,
        files = files)

    analysis <- showFileClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

